// init.js - a wrapper JavaScript file containing constants.

const musicData = [
    {
        "title": "First Kiss and My Heart is 120BPM",
        "by": "Kyoung Seo",
        "file": "ijfnkGDLM1g",
        "by-color": "purple",
        id: 0,
    }, 
    {
        "title": "Ongoing",
        "by": "Kyoung Seo",
        "file": "GArleOgvtjs",
        "by-color": "purple",
        id: 1,
    }, 
    {
        "title": "Love Actually",
        "by": "Daybreak + Sunnyhill",
        "file": "MStMdxnrYyY",
        "by-color": "orange",
        id: 2,
    },
    {
        "title": "Discord",
        "by": "QWER",
        "file": "WGm2HmXeeRI",
        "by-color": "skyblue",
        id: 3,
    }, 
    {
        "title": "Secret Diary",
        "by": "QWER",
        "file": "MPK7oP1--4s",
        "by-color": "skyblue",
        id: 4,
    }, 
    {
        "title": "Harmony of Stars",
        "by": "QWER",
        "file": "On6Pm4M-dQQ",
        "by-color": "skyblue",
        id: 5,
    },
    {
        "title": "Your Shampoo Scent in the Flowers",
        "by": "Jang Bum Joon",
        "file": "_pcl_JPqMfw",
        "by-color": "brown",
        id: 6,
    },
    {
        "title": "HoRangPungRyuGa",
        "by": "SangRokSu (feat Narae)",
        "file": "fBQhY7tfx4k",
        "by-color": "pink",
        id: 7,
    },
    {
        "title": "Journey to Atlantis",
        "by": "La Boum",
        "file": "m0o7fbNKhpM",
        "by-color": "lightblue",
        id: 8,
        'start': 4,
        'end': 244,
    },
    {
        "title": "Me Gustas Tu",
        "by": "GFriends",
        "file": "oixRBiOteWY",
        "by-color": "magenta",
        id: 9,
    },
    {
        "title": "Rough",
        "by": "GFriends",
        "file": "RSh5akaaHXk",
        "by-color": "magenta",
        id: 10,
    },
    {
        "title": "La La La",
        "by": "Zamgolbers",
        "file": "ZBhicyvlhcg",
        "by-color": "blue",
        id: 11,
        'start': 3,
        'end': 196,
    },
    {
        "title": "Cheer Up",
        "by": "TWICE",
        "file": "c7rCyll5AeY",
        "by-color": "pink",
        id: 12,
    },
    {
        "title": "Time of Our Life (Zamgolbers Cover)",
        "by": "Zamgolbers",
        "file": "USb5I2t_nEo",
        "by-color": "blue",
        id: 13,
        "start": 30,
        "end": 210,
    }
];